### PR TITLE
Fix JupyterHub + Clean up

### PR DESCRIPTION
**Pull request by mhebrard**
* I clean up the sub scripts to clarify the installation flow (see below)
* The configuration and environment variables of spark are done by `aws emr` command
* Python3 is updated on MASTER and SLAVES
* Hail is build on MASTER
* Hail jar and python utilities are copied into `/opt/hail`. on MASTER and SLAVES, Only these files are needed for spark 
 
### Installation flow:
* install2.pl
  * load `hail02_EMR.yaml`
  * run `aws emr create-cluster`
  * wait for the cluster to be in `WAITING` status
  * display Master DNS
  * copy keys on `MASTER`
  * copy `hail_install.sh` on `MASTER`
  * run `hail_install.sh` on `MASTER`
    * copy keys on `SLAVES`
    * clone `c-BIG/hail-on-EMR` into `/opt/hail-on-EMR`
    * run `hail_python3.sh` on `MASTER`
      * update python3 and install dependencies
    * run `hail_update.sh` on `MASTER`
      * run `hail_build.sh`
        * clone `broadinstitute/hail` into `/opt/broad-hail`
        * build hail
        * copy `hail-all-spark.jar` and `hail/pyton/*` into `/opt/hail`
    * run `hail_python3.sh` on `SLAVES`
    * copy `/opt/hail/*` on `SLAVES`

### CODE REVIEW

**Comment by mhebrard** [comment]
@Jack-Ow 
Sorry for the confusion, I renamed most of the file to simplify: 
* the core of `install_hail_python36.sh` is in `hail_install.sh`
* the core of `hail_install_python3.sh` is `hail_python3.sh`
* the core of `update_hail.sh` is `hail_update.sh`
* the core of `hail_build.sh` is still `hail_build.sh`

**Comment by Jack-Ow** [comment]
@mhebrard , noted. Thanks.

**Comment by Jack-Ow** [comment]
@mhebrard, gotten this error. Can send me the additional line in yaml file? Thanks
'--region '+c['config']['REGION']

**Comment by mhebrard** [comment]
Oh sorry, I added region as parameter, forgot to mention it
Here the yaml file (I masked the fields `S3_BUCKET`, `KEY_NAME`, `PATH_TO_KEY`, `SUBNET_ID` as this post is public)

```yml
config:
  EMR_CLUSTER_NAME: "hebrardms-hail-mini-2" # Give a name to the EMR cluster
  EC2_NAME_TAG: "hebrardms-hail-mini-2" # Adds a tag to the individual EC2 instances
  OWNER_TAG: "hebrardms" # EC2 owner tag
  PROJECT_TAG: "npm-chorus" # Project tag
  REGION: "ap-southeast-1" # AWS Region tag
  S3_BUCKET: "s3n://<bucket>/EMR_logs" # Specify your S3 bucket for EMR log storage
  KEY_NAME: "<key>" # Input your key name DO NOT include the .pem extension
  PATH_TO_KEY: "<path>" # Full path to the FOLDER where the .pem file resides
  MASTER_INSTANCE_TYPE: "c5.4xlarge" # Suggested EC2 instances, change as desired
  CORE_INSTANCE_TYPE: "c5.4xlarge" # Suggested EC2 instances, change as desired
  CORE_COUNT: "1" # Number of nodes
  CORE_EBS_SIZE: "150" # ?
  SUBNET_ID: "<subnet>" # Set your private subnet ID
  CORE_SECURITY_GROUP: "" # If empty creates a new group by default.
  MASTER_SECURITY_GROUP: "" # If empty creates a new group by default.
  RELEASE_LABEL: "emr-5.24.0"
```

**Comment by mhebrard** [comment]
As discussed I edit the conda file to fix the version of the modules.

The current files are setup to work once merge on branch 5.24.
in order to test the code before merge, an edit is required.

* Pull the branch `f-copy-jar`
* Checkout on `f-copy-jar`
* Create conda environment according to `README.md`
* Create or edit `src/hail02_EMR.yaml` according to `README.md`
* Edit `src/hail_install.sh` ( on the loval branch only )

```sh
# line 27: set the script to clone branch f-copy-jar
git clone --single-branch --branch f-copy-jar  https://github.com/c-BIG/hail-on-EMR.git
```

* run installation script
```python src/install2.py```

> The EMR should be up and running

* connect to the master node and open a tunnel for sparkUI and jupyterHub

```sh
# Save Master node DNS
export MASTER= #[Master DNS]
# Open SSH tunnel: 9443:jupyter, 4041:spark
ssh -i <~/path/to/key.pem> -L 9443:$MASTER:9443 -L 4041:$MASTER:4041 hadoop@$MASTER
```

* Visite [JupyterHub] at <https://localhost:9443/hub/login>
  * Enter default username: `jovyan`
  * Enter default password: `jupyter`

**Comment by mhebrard** [comment]
I added python 3 in the conda env.
It is a good think we are working on different environment.
I am not sure what are the minimal requirements.
let me know if you are missing something else, I'll add it in.

For reference:

```sh
# Exit conda env
conda deactivate
# Remove conda env
conda env remove -n hail
# Create conda env
conda env create -f src/conda-env.yaml
# Activate conda env
conda activate hail
```

**Comment by Jack-Ow** [comment]
Encountered this error even after creating conda environment (see attached file for the env) :
Creating EMR...
Traceback (most recent call last):
  File "install2.py", line 205, in <module>
    main(parameters)
  File "install2.py", line 199, in main
    launch_emr(cluster_id, c)
  File "install2.py", line 33, in launch_emr
    details_EMR=client_EMR.describe_cluster(ClusterId=cluster_id)
  File "/home/owjl/miniconda2/envs/hail/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/owjl/miniconda2/envs/hail/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DescribeCluster operation: clusterId '{
    "ClusterId": "j-UAQG32W8NS2B"
}' is not valid.
[conda_env_hail.txt](https://github.com/c-BIG/hail-on-EMR/files/3732632/conda_env_hail.txt)

**Comment by mhebrard** [comment]
I added AWS CLI in the conda environment, with a fix version that work on my machine.
The good news is that we do not need to reconfigure the CLI. the credentials and key pairs are shared between the base environment and the hail one.

I also update the README file.

**Comment by mhebrard** [comment]
I couldn't find why in my environment `cluster_id_byte` is a string but in your environment it is a hash.
I edited `install2.py` to check if the type of this variable and parse it properly in both cases.
As I cannot test on my machine, please give it a try and let me know.

**Pull request merged**
